# syntax=docker/dockerfile:1
FROM pytorch/pytorch
LABEL Uday Jain <uday9k@gmail.com>
WORKDIR /pytorch
COPY requirements.txt requirements.txt
RUN pip install notebook
ENV TZ=UTC
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
RUN apt-get update && apt-get install -y make automake gcc g++ subversion && apt-get install -y libgl1-mesa-glx libgtk2.0-0 libsm6 libxext6 libgtk2.0-dev pkg-config && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y qt5-default libxcb-xinerama0-dev xvfb
RUN python -m pip install --no-cache-dir --upgrade -r requirements.txt pip
RUN pip install opencv-python
RUN python -m pip install -U albumentations --no-binary qudida,albumentations
EXPOSE 8888
# COPY . .
CMD ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token='albumentations'", "--NotebookApp.password=''"]
