version: '2'
services:
    datascience-notebook:
        build: .
        volumes:
            # - ./:/home/jovyan/work
            - ./:/tf/files
        ports:
            - 8888:8888
        container_name:   jupyter_notebook
        deploy:
          resources:
            reservations:
              devices:
              - driver: nvidia
                capabilities: [gpu]
