/*
 * This file was automatically generated by EvoSuite
 * Wed Mar 27 22:31:10 GMT 2024
 */

package assignment_bmi.src.main.java.assignment;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WeightHelper_ESTest extends WeightHelper_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.bmiCat(30.0, 1.0);
      assertEquals("Obese", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.bmiCat(200.0, 200.0);
      assertEquals("Check Input Values", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.bmi((-4151.0), 2.5);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.bmi(2.5, 0.0);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.bmiCat(0.0, Double.NaN);
      assertEquals("Check Input Values", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.bmi(1.0, 1.0);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.bmi(Double.NaN, (-676.0));
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      double double0 = weightHelper0.bmi(2660.9, 25.0);
      assertEquals(Double.NaN, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.bmiCat(78.02136788305228, 0.8360563770765534);
      assertEquals("Obese", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.bmiCat(18.5, 1.0);
      assertEquals("Normal weight", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.bmiCat(0.8360563770765534, 0.8360563770765534);
      assertEquals("Underweight", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.bmiCat(25.0, 1.0);
      assertEquals("Overweight", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      WeightHelper weightHelper0 = new WeightHelper();
      String string0 = weightHelper0.bmiCat((-676.0), (-1.0));
      assertEquals("Check Input Values", string0);
  }
}
